// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT-i8cbHXj27iv-zQFbPYvdcWF_kd77Xk',
    appId: '1:296494977896:web:27427df101dd7c7052fcdd',
    messagingSenderId: '296494977896',
    projectId: 'emergence-66b62',
    authDomain: 'emergence-66b62.firebaseapp.com',
    storageBucket: 'emergence-66b62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQMkOQUt6L6upknPEVEsWXT1ihnHt3ZQ4',
    appId: '1:296494977896:android:f0b44559580c125052fcdd',
    messagingSenderId: '296494977896',
    projectId: 'emergence-66b62',
    storageBucket: 'emergence-66b62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3qUC8ixukGqlVD0NjrrancYtbQQmbc-M',
    appId: '1:296494977896:ios:6feba05e7feaf15f52fcdd',
    messagingSenderId: '296494977896',
    projectId: 'emergence-66b62',
    storageBucket: 'emergence-66b62.appspot.com',
    iosBundleId: 'com.example.emergence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3qUC8ixukGqlVD0NjrrancYtbQQmbc-M',
    appId: '1:296494977896:ios:6feba05e7feaf15f52fcdd',
    messagingSenderId: '296494977896',
    projectId: 'emergence-66b62',
    storageBucket: 'emergence-66b62.appspot.com',
    iosBundleId: 'com.example.emergence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT-i8cbHXj27iv-zQFbPYvdcWF_kd77Xk',
    appId: '1:296494977896:web:6c0490c1657d0c8f52fcdd',
    messagingSenderId: '296494977896',
    projectId: 'emergence-66b62',
    authDomain: 'emergence-66b62.firebaseapp.com',
    storageBucket: 'emergence-66b62.appspot.com',
  );
}
